version: '3'

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "3001:3000"

  backend:
    image: node:18
    container_name: backend
    command: node -e "console.log('Backend running')"

  redis:
    image: redis
    container_name: redis
